CREATE TABLE EMPLOYEE_DETAILS (EMPLOYEE_ID Serial PRIMARY KEY, FirstName VARCHAR,	LastName VARCHAR, Email VARCHAR UNIQUE, PhoneNumber BIGINT UNIQUE,
	HireDate DATE , Salary NUMERIC(10,2) CHECK(SALARY>25000.00), DepartmentID Integer, IsActive BOOLEAN NOT NULL , JobTitle VARCHAR DEFAULT('IT')
);
